version: "3.3"

services:
  api:
    build: ./api
    container_name: api-service
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development

  web:
    build: ./web
    container_name: web-service
    ports:
      - "5173:5173"
    volumes:
      - ./web:/usr/src/app
      - ./web/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    depends_on:
      - api
